# Generated by Django 4.0.4 on 2022-09-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ins', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
