# Generated by Django 4.0.4 on 2022-09-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='img',
        ),
    ]
