# Generated by Django 4.0.4 on 2022-09-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didac', '0002_remove_cards_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='file',
            field=models.FileField(default=1, upload_to=''),
        ),
    ]
